Added a forward for successfully uploaded demos
demostf/plugin pull request #7
Opened 2022-12-02 01:48 UTC by TheBv

Adds a forward that gets called when a successful api request was made. 
This allows other plugins to access the url or id for the successfully uploaded demo.

2022-12-02 15:29 UTC, icewind1991 commented
Can you replace the regex with a simple string prefix match/substring so it doesn't add a dependency?

2022-12-02 15:45 UTC, TheBv commented
I'll look into it but. It's just that getting the id for the log from a url that potentially has multiple slashes in it (e.g `demos.tf/demos/123`) is quite cumbersome.

2022-12-02 17:42 UTC, c43721 requested changes

2022-12-02 17:42 UTC, c43721 commented on include/demostf.inc
> +
nit: extra new line :)

2022-12-02 17:42 UTC, c43721 commented on demostf.sp
> +	Call_PushString(url);
I assume this is modeled after logs.tf?

2022-12-02 21:04 UTC, icewind1991 commented
> I'll look into it but. It's just that getting the id for the log from a url that potentially has multiple slashes in it (e.g demos.tf/demos/123) is quite cumbersome so I wanted to avoid that.

The output format for success is very consistent so checking that it starts with `STV available at: ` and getting the demo id from a fixed offset should work and keep working. (the webui upload does basically the same thing)

2022-12-04 18:15 UTC, TheBv commented on demostf.sp
> +	Call_PushString(url);
Pretty much

2022-12-04 18:18 UTC, TheBv commented
I went ahead and replaced the regex with string stuff.
Yes the part in regards to id's is a bit much but I wanted to make sure to cover the case were someone might end up using a different url to post too. e.g. `demos2.tf/demos/123` and this seemed like the only simple way of achieving this.

2022-12-07 16:12 UTC, icewind1991 approved these changes

2022-12-07 16:12 UTC, merged